// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VPM.Data;

namespace VPM.Migrations
{
    [DbContext(typeof(VPMDBContext))]
    [Migration("20201016233528_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VPM.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("VatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Sample Address A",
                            Name = "Sample Costumer A",
                            VatNumber = "500500500",
                            ZipCode = "4470"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Sample Address B",
                            Name = "Sample Costumer B",
                            VatNumber = "500500501",
                            ZipCode = "4471"
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "Sample Address C",
                            Name = "Sample Costumer C",
                            VatNumber = "500500502",
                            ZipCode = "4472"
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "Sample Address D",
                            Name = "Sample Costumer D",
                            VatNumber = "500500503",
                            ZipCode = "4473"
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "Sample Address E",
                            Name = "Sample Costumer E",
                            VatNumber = "500500504",
                            ZipCode = "4474"
                        });
                });

            modelBuilder.Entity("VPM.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("ProjectId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            CreateDate = new DateTime(2020, 10, 15, 0, 35, 28, 602, DateTimeKind.Local).AddTicks(7991),
                            CustomerId = 1,
                            DeliveryDate = new DateTime(2020, 10, 27, 0, 35, 28, 604, DateTimeKind.Local).AddTicks(8571),
                            Description = "Sample Project Description A1",
                            Title = "Sample project A1"
                        },
                        new
                        {
                            ProjectId = 2,
                            CreateDate = new DateTime(2020, 10, 15, 0, 35, 28, 605, DateTimeKind.Local).AddTicks(174),
                            CustomerId = 4,
                            DeliveryDate = new DateTime(2020, 12, 6, 0, 35, 28, 605, DateTimeKind.Local).AddTicks(201),
                            Description = "Sample Project Description D2",
                            Title = "Sample project D2"
                        },
                        new
                        {
                            ProjectId = 3,
                            CreateDate = new DateTime(2020, 10, 7, 0, 35, 28, 605, DateTimeKind.Local).AddTicks(225),
                            CustomerId = 2,
                            DeliveryDate = new DateTime(2020, 11, 10, 0, 35, 28, 605, DateTimeKind.Local).AddTicks(228),
                            Description = "Sample Project Description B3",
                            Title = "Sample project B3"
                        });
                });

            modelBuilder.Entity("VPM.Models.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("BillableTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CostPerHour")
                        .HasColumnType("decimal(16,4)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TaskCost")
                        .HasColumnType("decimal(16,4)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("TaskId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Task");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            BillableTime = new DateTime(2020, 10, 16, 23, 45, 28, 605, DateTimeKind.Local).AddTicks(1214),
                            CostPerHour = 4.215m,
                            CreateDate = new DateTime(2020, 10, 15, 0, 35, 28, 605, DateTimeKind.Local).AddTicks(2643),
                            Description = "Task Project 1",
                            ProjectId = 1,
                            Title = "Task Project 1"
                        });
                });

            modelBuilder.Entity("VPM.Models.Project", b =>
                {
                    b.HasOne("VPM.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VPM.Models.Task", b =>
                {
                    b.HasOne("VPM.Models.Project", "Project")
                        .WithMany("Task")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
